#https://www.linode.com/docs/guides/wordpress-with-docker-compose/
version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wordpress_files:/var/www/html  
       - wordpress_files:/var/www/html
     ports:
       - "81:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql  
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_DATABASE: "${MYSQL_DATABASE}"
       MYSQL_USER: "${MYSQL_USER}"
       MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"

   phpmyadmin:
     image: "phpmyadmin"
     restart: always
     links:
        - db
     environment:
       PMA_HOST: db
       PMA_PORT: 3306
       PMA_USER: root
       PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_USER: "${MYSQL_USER}"
       MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
       UPLOAD_LIMIT: "${UPLOAD_LIMIT}"
       MEMORY_LIMIT: "${MEMORY_LIMIT}"
     ports:
       - "8080:80"
     volumes:
       - ./php/config:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
volumes:
    wordpress_files:
    db_data:


#Create .env file
MYSQL_ROOT_PASSWORD=school
MYSQL_DATABASE=wordpress
MYSQL_USER=wordpress
#MYSQL_PASSWORD=admin1

#Phpmyadmin
UPLOAD_LIMIT=512M
MEMORY_LIMIT=512M

#Wordpress
WORDPRESS_DB_USER=wordpress
WORDPRESS_DB_PASSWORD=admin1